services:
  - type: web
    name: maraphoto-backend
    env: node
    plan: free
    rootDir: backend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 5000
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_REFRESH_SECRET
        generateValue: true
      - key: GOOGLE_CLIENT_ID
        value: 486978416692-98vmof7b7n5hrrbn6diaj7marsqrm3ar.apps.googleusercontent.com
      - key: CLOUDINARY_URL
        sync: false
      - key: REDIS_HOST
        value: 127.0.0.1
      - key: REDIS_PORT
        value: 6379
      - key: SMTP_HOST
        value: smtp.gmail.com
      - key: SMTP_PORT
        value: 587
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
